/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Simulacion.Controlador;

/**
 *
 * @author sergio
 */
public class GuiCorredor extends javax.swing.JFrame {

    /**
     * Creates new form GuiCorredor
     */
    public GuiCorredor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBsimular = new javax.swing.JButton();
        jCBhorario = new javax.swing.JComboBox();
        jLhorario = new javax.swing.JLabel();
        jLvehiculos = new javax.swing.JLabel();
        jCBcarro = new javax.swing.JCheckBox();
        jCBbuseta = new javax.swing.JCheckBox();
        jCBcamion = new javax.swing.JCheckBox();
        jCBmio = new javax.swing.JCheckBox();
        jCBtodos = new javax.swing.JCheckBox();
        jTPresultados = new javax.swing.JTabbedPane();
        jCBsemaforo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBsimular.setText("Prueba");
        jBsimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsimularActionPerformed(evt);
            }
        });

        jCBhorario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "7   - 8am", "12 - 2 pm", "6   - 8 pm" }));

        jLhorario.setText("Horarios");

        jLvehiculos.setText("Tipos de vehiculos");

        jCBcarro.setSelected(true);
        jCBcarro.setText("Carro");
        jCBcarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBcarroMouseClicked(evt);
            }
        });

        jCBbuseta.setSelected(true);
        jCBbuseta.setText("Buseta");
        jCBbuseta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBbusetaMouseClicked(evt);
            }
        });

        jCBcamion.setSelected(true);
        jCBcamion.setText("Camión");
        jCBcamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBcamionMouseClicked(evt);
            }
        });

        jCBmio.setSelected(true);
        jCBmio.setText("MIO");
        jCBmio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBmioMouseClicked(evt);
            }
        });

        jCBtodos.setSelected(true);
        jCBtodos.setText("Todos");
        jCBtodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBtodosMouseClicked(evt);
            }
        });

        jCBsemaforo.setSelected(true);
        jCBsemaforo.setText("Incluir semaforos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBsimular)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBtodos)
                            .addComponent(jCBmio)
                            .addComponent(jCBcamion)
                            .addComponent(jCBbuseta)
                            .addComponent(jLvehiculos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                        .addComponent(jLhorario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBhorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTPresultados, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCBcarro)
                                .addGap(92, 92, 92)
                                .addComponent(jCBsemaforo)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBhorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLhorario))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLvehiculos)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBcarro)
                            .addComponent(jCBsemaforo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBbuseta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBcamion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBmio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBtodos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTPresultados, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBsimular)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsimularActionPerformed
        int[] horario = {0, 0, 0};
        //ArrayList vehiculos = new ArrayList();
        int [] vehiculos = {0,0,0,0};
        int horarioSeleccionado = jCBhorario.getSelectedIndex();
        
        
        // seteo de horarios
        switch (horarioSeleccionado) {
            case 0:
                for (int i = 0; i < horario.length; i++)
                    horario[i] = 1;
                break;
            case 1:
                horario[0] = 1;
                break;
            case 2:
                horario[1] = 1;
                break;
            case 3:
                horario[2] = 1;
                break;
        }
        
        // seteo de vehiculos
        if (jCBtodos.isSelected()) {
            for (int i = 0; i <= 3; i++)
                //vehiculos.add(i);
                vehiculos[i]= i +1; 
        }else {
            
            if (jCBcarro.isSelected())
                //vehiculos.add(1);
                vehiculos[0] = 1;
                
            if (jCBbuseta.isSelected())
                //vehiculos.add(2);
                vehiculos[1] = 2;
                //index++;
            if (jCBcamion.isSelected())
                //vehiculos.add(3);
                vehiculos[2] = 3;
                //index++;
            if (jCBmio.isSelected())
                //vehiculos.add(4);
                vehiculos[3] = 4;
                //index++;
        }
        // llamada a controlador principal
        Controlador.main(horario, vehiculos);
    }//GEN-LAST:event_jBsimularActionPerformed

    private void jCBtodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBtodosMouseClicked
        // TODO add your handling code here:
        if (jCBtodos.isSelected()) {
            
            jCBcarro.setSelected(true);
            jCBbuseta.setSelected(true);
            jCBcamion.setSelected(true);
            jCBmio.setSelected(true);
        
        }else {
            
            jCBcarro.setSelected(false);
            jCBbuseta.setSelected(false);
            jCBcamion.setSelected(false);
            jCBmio.setSelected(false);
        }
    }//GEN-LAST:event_jCBtodosMouseClicked

    private void jCBcarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBcarroMouseClicked
        // TODO add your handling code here:
        if (jCBcarro.isSelected())
            jCBtodos.setSelected(false);
    }//GEN-LAST:event_jCBcarroMouseClicked

    private void jCBbusetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBbusetaMouseClicked
        // TODO add your handling code here:
        if (jCBcarro.isSelected())
            jCBtodos.setSelected(false);
    }//GEN-LAST:event_jCBbusetaMouseClicked

    private void jCBcamionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBcamionMouseClicked
        // TODO add your handling code here:
        if (jCBcarro.isSelected())
            jCBtodos.setSelected(false);
    }//GEN-LAST:event_jCBcamionMouseClicked

    private void jCBmioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBmioMouseClicked
        // TODO add your handling code here:
        if (jCBcarro.isSelected())
            jCBtodos.setSelected(false);
    }//GEN-LAST:event_jCBmioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCorredor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBsimular;
    private javax.swing.JCheckBox jCBbuseta;
    private javax.swing.JCheckBox jCBcamion;
    private javax.swing.JCheckBox jCBcarro;
    private javax.swing.JComboBox jCBhorario;
    private javax.swing.JCheckBox jCBmio;
    private javax.swing.JCheckBox jCBsemaforo;
    private javax.swing.JCheckBox jCBtodos;
    private javax.swing.JLabel jLhorario;
    private javax.swing.JLabel jLvehiculos;
    private javax.swing.JTabbedPane jTPresultados;
    // End of variables declaration//GEN-END:variables
}
